import Head from 'next/head'
import Link from 'next/link'
import { baseUrl, fetchApi } from '../utils/fetchApi'
import Hero from '../components/Hero'
import Property from '../components/Property'
import {BsArrowRight} from 'react-icons/bs'
import CountUp from '../HomeLayout/CountUp'
import Clients from '../HomeLayout/Clients'
import ContactUs from '../HomeLayout/ContactUs'
import Footer from '../components/Footer'

export default function Home({propertiesForSale, propertiesForRent}) {
  // console.log(propertiesForSale, propertiesForRent);
  return (
    <div>
      <Head>
        <title>Lhary Homes | Real Estate Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero/>
      <div className='bg-[#f5f5f5]'>
        <div className='px-2 max-w-[1110px] w-full mx-auto'>
          <div className=' pt-6'>
            <div className='flex cursor-pointer bg-gray-100 border border-gray-200 p-2 text-xl rounded-md justify-center items-center font-bold'>
                <Link href='/PropertyFilter'>Search Property By Category</Link> <BsArrowRight className='inline ml-2'/>
            </div>
          </div>
          <div className='w-full h-full py-16'>
            <div className='flex flex-col gap-10'>
              <div>
                <h1 className='text-[#0eafef] text-3xl tracking-widest font-bold py-2'>Properties For Rent</h1>
                <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8'>
                  {propertiesForRent?.map((property) => <Property property= {property} key={property.id}/>)}
                </div>
              </div>

              <div>
                <h1 className='text-[#0eafef] text-3xl tracking-widest font-bold py-2'>Properties For Sale</h1>
                <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8'>
                  {propertiesForSale?.map((property) => <Property property= {property} key={property.id}/>)}
                </div>
              </div>
            </div>
          </div>  
        </div>
      </div>
      <CountUp/>
      <Clients/>
      <ContactUs/>
      <Footer/>
    </div>
  )
}

export async function getStaticProps() {
  const propertyForRent = await fetchApi(`${baseUrl}/properties/list?locationExternalIDs=5002%2C6020&purpose=for-rent&hitsPerPage=6`);
  const propertyForSale = await fetchApi(`${baseUrl}/properties/list?locationExternalIDs=5002%2C6020&purpose=for-sale&hitsPerPage=6`);
  

  return {
    props: {
      propertiesForSale: propertyForSale?.hits,
      propertiesForRent: propertyForRent?.hits,
    },
  };
}